#! /bin/bash
source /users/onl/.topology

numRtrs=6

host[1]=$h4x2
host[2]=$h7x1
host[3]=$h2x3
host[4]=$h5x2
host[5]=$h6x1
host[6]=$h2x4

i=1
while [ $i -le ${numRtrs} ] ; do
	ssh ${host[$i]} killall python &
	i=$((i+1))
done
