#! /bin/bash
iperfBw=$1
dropProb=0
delta=.001
source /users/onl/.topology
echo "dropProb=" $dropProb " delta=" $delta
ssh $h7x1 "cd Studio4; java TestMonitor h7x1 11313 10 ${dropProb} \
    ${delta} >srvOut1 &"
ssh $h5x2 /usr/bin/iperf -c h6x1 -u -b ${iperfBw}m -l 1000 -t 10 &
ssh $h4x2 "cd Studio4; java TestMonitor h4x2 0 10 ${dropProb} \
    ${delta} h7x1 11313 >cliOut1"
sleep 2
echo "************** client report ****************"
cat cliOut1
sleep 5
echo "************** server report ****************"
cat srvOut1
