#!/bin/bash
source /users/onl/.topology

password=$1

host[1]=$h1x2
host[2]=$h1x3
host[3]=$h2x2
host[4]=$h2x3
host[5]=$h2x4

i=1
while [ $i -le 5 ] ; do
	sshpass -p $password scp Listener.java Sender.java ${host[$i]}:~/
	sshpass -p $password ssh ${host[$i]} "cd ~/; javac *.java"
	i=$((i+1))
done

sshpass -p $password ssh $h1x2 "cd ~/; java Listener h1x2 > out1" &
sshpass -p $password ssh $h1x3 "cd ~/; java Listener h1x3 > out2" &
sleep 1
sshpass -p $password ssh $h2x2 "cd ~/; java Sender 192.168.1.2 11313 30123 h2x2" &
sshpass -p $password ssh $h2x3 "cd ~/; java Sender 192.168.1.3 11313 30123 h2x3" &
sshpass -p $password ssh $h2x4 "cd ~/; java Sender 192.168.1.2 11313 30123 h2x4" &

sleep 5

sshpass -p $password scp $h1x2:~/out1 ~/473/lab6
sshpass -p $password scp $h1x3:~/out2 ~/473/lab6

echo "********** out1 **********"
cat out1
echo "********** out2 **********"
cat out2

sshpass -p $password ssh $h2x2 "cd ~/; java Listener > out3" &
sshpass -p $password ssh $h2x3 "cd ~/; java Listener > out4" &
sleep 1
sshpass -p $password ssh $h1x2 "cd ~/; java Sender 192.168.2.2 11313 30123 h1x2" &
sshpass -p $password ssh $h1x3 "cd ~/; java Sender 192.168.2.3 11313 30123 h1x3" &

sleep 5

sshpass -p $password scp $h2x2:~/out3 ~/473/lab6
sshpass -p $password scp $h2x3:~/out4 ~/473/lab6

echo "********** out3 **********"
cat out3
echo "********** out4 **********"
cat out4
